image: ahmedmorad101/openjdk23-maven


stages:
- test
- checkstyle

junit_tests:
  stage: test
  script:
    - mvn test
  tags:
    - docker
  artifacts:
    reports:
      junit:
        - target/surefire-reports/*.xml

checkstyle:
  stage: checkstyle
  script:
    - mvn clean install checkstyle:check
  tags:
    - docker
  artifacts:
    paths:
      - target/checkstyle-result.xml
