image: ahmedmorad101/openjdk23-maven


stages:
- test
- checkstyle

junit_tests:
  stage: test
  script:
    - mvn test
  tags:
    - docker
  artifacts:
    reports:
      junit:
        - target/surefire-reports/*.xml

checkstyle:
  stage: checkstyle
  script:
    - mvn clean install checkstyle:check
    - java -jar gitlab-code-quality-plugin.jar checkstyle-result.xml gl-code-quality-report.json
  tags:
    - docker
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
